### ISSUE TITLE
Automate merges up

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/gha-ci#17] opened 2021-12-03 02:43 UTC
# Story

As a maintainer, I want patch in older minor releases to automatically flow up to later minor releases.

**Comment by GuySartorelli** [comment] 2022-05-19 23:33
Related: silverstripe/silverstripe-framework#9083

**Comment by GuySartorelli** [comment] 2023-07-11 04:52
Duplicate of https://github.com/silverstripeltd/product-issues/issues/753

**Closed as not planned by GuySartorelli** 2023-07-11 04:52 UTC
